### ISSUE TITLE
/roll 1d100 produces the right result but claims to be a d10.

### ISSUE THREAD

**Issue by kavaliro** [rossimo/dice#13]

**Comment by rossimo** [comment]
Is this on mobile?

**Comment by Tungul** [comment]
Yes. https://puu.sh/qnsRp/e66403ec65.png

**Comment by kavaliro** [comment]
Yes, mobile.

**Comment by rossimo** [comment]
Can you replicate this on desktop? I think this maybe an issue with Slack mobile rendering.

**Comment by Tungul** [comment]
I'm pretty sure I didn't see it occurring on desktop at all, and not on that same one I took a picture of above.

**Comment by rossimo** [comment]
Confirmed as a Slack mobile rendering bug.
